### ISSUE TITLE
Faulty calculation of factorial of n in fac.m 

### ISSUE THREAD

**Issue by Senira** [joergbrech/modsim2-projektbeschreibung#1]
The bug of the function fac is located in line 17. 
The calculation of the factorial of n is faulty and needs to be corrected.

**Comment by joergbrech** [comment]
@Senira, I think this issue was accidentally opened in this *template* repository, while it should have been opened in https://github.com/hbrs-cse/aufgabe-1-projektbeschreibung-dynamischesduo? 🙂
